### ISSUE TITLE
Slight conflict with KeeTheme and custom password font size

### ISSUE THREAD

**Issue by ziesemer** [Rookiestyle/ColoredPassword#10]
## Overview

When combined with [KeeTheme](https://github.com/xatupal/KeeTheme) *and* a larger custom password font size, the password text in an entry does not appear properly:

![image](https://user-images.githubusercontent.com/1887649/132135261-e68519ee-6873-411b-9f54-1892f64e552e.png)

## Steps to Reproduce
1. Configure a custom Password Font in native KeePass.  (I'm using size 16 here.)
![image](https://user-images.githubusercontent.com/1887649/132135423-f3443328-f783-4331-8351-39d5e391bece.png)
2. Install KeeTheme, and enable Dark Theme.
3. Install and enable ColoredPassword.

## Expected Behavior
Passwords should continue to display properly and fully.

ColoredPassword probably needs to provide an option to not set a background color at all / have a transparent background option?  As-is and by default, it is set to white, which I'm guessing is interfering here.  (I did try setting the background to black, but there also appears to be some sort of a border that is drawn along with it and over the password text that I can't seem to work around.)

## Actual Behavior

See the first screenshot under the Overview.

Here are some additional screenshots, showing the various combinations of the custom font size, Dark Theme, and/or Colored Password:

Default:
![image](https://user-images.githubusercontent.com/1887649/132135728-073337c8-2b44-4719-872e-0efad8bf1db5.png)

Dark Theme (only):
![image](https://user-images.githubusercontent.com/1887649/132135753-c1bd3436-3b52-4fdc-9118-8dd505737eb3.png)

Colored Password (only):
![image](https://user-images.githubusercontent.com/1887649/132135766-e69952c8-7c9d-4a2e-ab84-06601089d5e5.png)

Dark Theme and Colored Password:
![image](https://user-images.githubusercontent.com/1887649/132135777-727ec15a-2da3-4c4f-a23c-19d1396ee23d.png)

Custom Font Size (only):
![image](https://user-images.githubusercontent.com/1887649/132135781-ec1ec47e-9a23-4fcb-8008-70da10cd3405.png)

Custom Font Size and Colored Password:
![image](https://user-images.githubusercontent.com/1887649/132135785-6f24186b-b8e9-4d80-87e9-56e641835993.png)

Custom Font Size and Dark Theme:
![image](https://user-images.githubusercontent.com/1887649/132135801-1f21b6f3-3ffa-4950-96a3-b904ec93e014.png)

## Context
OS: Windows10 21H1 (OS Build 19043.1165)
KeePass Version: 2.48.1
ColoredPassword Plugin Version: 0.11.5
KeeTheme Plugin Version 0.9.2.0

**Comment by Rookiestyle** [comment]
I do not plan to add a *no background color change* option or a transparent background color, this would result in a very complex UI.

The next release will have improved KeeTheme detection and won't set the background color if KeeTheme is active.
You still need to assign readable foregound colors, e. g. black letters (ColoredPassword) and dark background (keeTheme) won't be a good combination.

**Comment by ziesemer** [comment]
@Rookiestyle  - 0.12.1.0 actually made this worse, when compared to the original screenshots provided above:
![image](https://user-images.githubusercontent.com/1887649/132545805-609271b7-589e-4ae1-ad00-fd796f6fc8c5.png)
The characters are now not only "broken", but the lower portions are completely missing / invisible.

**Comment by Rookiestyle** [comment]
I tend to consider this a KeeTheme issue.

To show different colors in a textbox, a so called RichTextBox needs to be used.
KeeTheme creates a container for each and every RichTextBox it detects.
As of now, this will disrupt keyboard navigation and also does not react on KeePass changing the size of the RichTextBox when a non-default font is used.

I created a pull request for KeeTheme as this potentially impacts other plugins as well: xatupal/keetheme#60 
If this pull request will not be merged, I'll release an updated version of ColoredPassword.

Meanwhile, you can try [pre-release 0.12.0.1](https://github.com/Rookiestyle/ColoredPassword/releases/tag/v0.12.0.1)
Let me know whether this solves the issue.

**Comment by ziesemer** [comment]
Much better - thanks!!
![image](https://user-images.githubusercontent.com/1887649/132559456-12c0c48e-8692-49d3-bec6-13ce64d731d9.png)
