### ISSUE TITLE
Focus issues

### ISSUE THREAD

**Issue by Rookiestyle** [Rookiestyle/ColoredPassword#11]
With the release of KeePass 2.49, two issues can be observed

Unhiding a password does no longer place the cursor in the password input field / does not focus the password input field properly
This affects all forms where passwords can be shown in plaintext (masterkey prompt, masterkey change, entry form, ...)

Additionally in the masterkey forms, focus is lost when you enter a character into an empty password input field.

Both can easily be worked around by simply placing the cursor in the password input field again.

A fix is in progress

**Comment by TBugReporter** [comment]
Still not fixed. Cross reference:  https://sourceforge.net/p/keepass/bugs/2095/?limit=250#19eb

**Comment by Rookiestyle** [comment]
What exactly is not fixed?

1. Not placing the cursor in the password field after disabling protection?
2. Focus loss after entering the first character in the password field with protection disabled?
3. Key file combobox initially focused as mentioned in your crosspost? Password protection is enabled initially, right?

All?

I can't reproduce any of the above issues and need more information. Attaching a debug file hopefully helps.

**Comment by TBugReporter** [comment]
As I explained on SourceForge, when CP is present, starting KeePass and then hitting Alt-F,R,{#} opens the Enter Master Key dialog, but with the focus in the Key File dropdown instead of the Enter Password field.  Shutting down KeePass, removing CP, and restarting reverts KeePass to the previous (expected) behavior.
(I wrongly assumed that this was a result of the new KeePass version alone.)
Once I get the cursor back into the password field, everything else (as of your latest version) is as expected.

**Comment by Rookiestyle** [comment]
On my device, behaviour is as follows
Alt+F, R, 1 shows the Enter Master Key dialog for the first db in File -> Open Recent
Alt+F, R, 2 shows the Enter Master Key dialog for the second db in File -> Open Recent
...

The password field is focused all the time


Just to be sure: 
- You face this issue with ColoredPassword being the only installed plugin?
- What happens if you deactivate ColoredPassword in Tools -> Options...?

> Attaching a debug file hopefully helps

https://github.com/Rookiestyle/ColoredPassword/wiki/Create-a-debugfile
There should be nothing specific to the Enter Master Key Dialog in Colored Password but the debug file will show all other plugins, Windows and .NET version

**Comment by TBugReporter** [comment]
> * You face this issue with ColoredPassword being the only installed plugin?

Yes.
![Screenshot 1](https://user-images.githubusercontent.com/16196686/133171037-e4c14c56-41e7-4f9c-bdda-2b00215d6ad9.png)

> * What happens if you deactivate ColoredPassword in Tools -> Options...?

Behavior reverts to expected.
![Screenshot 2](https://user-images.githubusercontent.com/16196686/133171038-9248f571-e92d-4ae3-a1dc-cb8779df8a3f.png)

> > Attaching a debug file hopefully helps

Here are two. (File extensions changed to meet github restrictions.)
[Debug_ColoredPassword_1.xml.txt](https://github.com/Rookiestyle/ColoredPassword/files/7157932/Debug_ColoredPassword_1.xml.txt)
[Debug_ColoredPassword_2.xml.txt](https://github.com/Rookiestyle/ColoredPassword/files/7157931/Debug_ColoredPassword_2.xml.txt)

**Comment by Rookiestyle** [comment]
Thanks for the debug files.
The files contain 
~~~
<Method>ApplyKeyUIFlags (KeePass.UI.UIUtil)</Method>
~~~

Based on that I assume you have UIFlag UncheckHidePassword active  and that answers my question reg. password protection enabled status

https://keepass.info/help/base/keys.html
Flag (hex): 0x8000000 
Flag (dec): 134217728 
Description: Uncheck 'hide password' option/button.

Most likely, you will experience the same behaviour when changing the masterkey

I will provide a fix for that asap.

**Comment by TBugReporter** [comment]
> Most likely, you will experience the same behaviour when changing the masterkey

I hadn't thought to test that until now, but yes, you're right.

**Comment by Rookiestyle** [comment]
I was not aware of the UIFlag to automatically unhide passwords when opening a database.
The new release 0.13.1 should work in that case

**Comment by TBugReporter** [comment]
Confirmed; thank you.
