### ISSUE TITLE
Enhancement possibility?

### ISSUE THREAD

**Issue by TBugReporter** [Rookiestyle/ColoredPassword#13]
Would you consider an enhancement to this plugin as described [here](https://sourceforge.net/p/keepass/discussion/329220/thread/d5ca816da7)?  Paul dismisses it as unnecessary, but I can understand the difficulty that it addresses - maybe add some sort of configuration option, normally off, to turn it on for additional fields?

**Comment by Rookiestyle** [comment]
To use colors you need to use a RichTextbox. 
My plugin replaces the SecureTextBox controls used for passwords by a RichTextBox - only if passwords are show. It uses a hook method provided by KeePass to do so. This way my plugin is informed whenever a password field is created.

This is not possible for any other textbox. KeePass would need to create them in a different way.
