### ISSUE TITLE
uppercase versus lowercase

### ISSUE THREAD

**Issue by Xtraim** [Rookiestyle/ColoredPassword#14]
## Summary
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Provide a brief overview of what the new feature is all about)
I use strongbox on my personal phone and i found very cool the fact thant uppercase and lowercase not the same colour.
If you can add it i will be very greatfull !

## Added value
[NOTE]: # (Describe how you and other users would benefit from this feature)

## Example
[NOTE]: # (Show a picture or a mock-up if applicable)

**Comment by Rookiestyle** [comment]
I'm sorry but this plugin is for the original KeePass only, which is a Windows application using .NET.
Different colors for upper and lower case are supported already.

I don't have the capabilities to develop smartphone versions.
