### ISSUE TITLE
Caps Lock warning appears when not needed, and won't go away

### ISSUE THREAD

**Issue by TBugReporter** [Rookiestyle/ColoredPassword#15]
## Cross reference:
https://sourceforge.net/p/keepass/bugs/2156/

## Steps to Reproduce
1. Set `KeyPromptFlags` to `134217728` ("Uncheck 'hide password' option/button") in `KeePass.config.xml`.
2. Start KeePass, hit Caps Lock, and try to open a database.

## Actual Behavior
KeePass ignores the config setting and displays an unnecessary and normally (without your plugin) suppressed warning balloon, which won't go away when Caps Lock is toggled.

**Comment by Rookiestyle** [comment]
I can't reproduce it this way:
* Set KeyPromptFlags to 134217728
* Start KeePass
* Hit Caps Lock
* Open a database

When I do that, no warning balloon is displayed, neither with ColoredPassword being active or inactive
Instead, password can simply be entered and it's not hidden by asterisks
Manually toggling hide/unhide toggles the warning balloon as expected

I assume you use KeePass 2.51.1, ColoredPassword 0.13.1 and there are no other plugins loaded?
Which OS and .NET do you use?

**Comment by TBugReporter** [comment]
I apologize for the incomplete testing.  CP alone won't do it for me either, but CP plus KeeTheme brings it back.  I guess you'll need to confer with Krzysztof to fix this.

**Comment by Rookiestyle** [comment]
This is related to [DwmSetWindowAttribute](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute) used by KeeTheme starting with KeeTheme 0.9.2 to color a window's title bar.

I'm trying to work around that without the need to change KeeTheme. If I don't succeed, I'll ask Krzysztof to change his way of using this function.

**Comment by TBugReporter** [comment]
I just found out that Dominik's KeeResize plugin also causes this same problem.  Maybe there's a way for him to deal with this in the main program, so that plugin creators won't need to make lists of plugins that their plugin won't work with...?

**Comment by Rookiestyle** [comment]
I don't think there's a way to deal with this in the main program.


My plugin needs to exchange the textbox shipped with KeePass by another one that is able to show colors.
This was done when the passwords are shown in plaintext - e. g. clicking the 3 dot button or using KeyPromptFlags like in your case.
Seems that replacing the textbox AND caps lock being on AND the form itself not yet being shown (event Shown) don't play nicely.

v0.14.1 now delays unhiding and you should not see this behaviour any longer.

I tested it with no other plugins running, ColoredPassword + KeeTheme, ColoredPassword + KeeResize, ColoredPassword + KeeTheme + KeeResize

**Comment by TBugReporter** [comment]
Works as expected; thank you.
