### ISSUE TITLE
"(Multiple values)"

### ISSUE THREAD

**Issue by TBugReporter** [Rookiestyle/ColoredPassword#19]
For your consideration:  When multiple entries are selected for simultaneous editing, and they have different passwords, KeePass indicates this by inserting the text "(Multiple values)" in the password field.  Your plugin colorizes this phrase, as if it were the actual password for all the selected records, failing to recognize the special nature of this phrase, and possibly implying that the phrase is actually the current value in all of the selected records.  Other fields (and this field when your plugin isn't running) show this string in gray when present; I suggest you modify your plugin to do the same.

**Comment by Rookiestyle** [comment]
I'm working on it, thanks for the hint
