### ISSUE TITLE
Selected password includes non-existing space

### ISSUE THREAD

**Issue by sergeevabc** [Rookiestyle/ColoredPassword#20]
Windows 7 x64, Keepass 2.52, ColoredPassword 0.15

Plugin is _off_. Everything's fine.

![image](https://user-images.githubusercontent.com/373718/201122802-ef2cc24b-980c-4ece-8ad1-a41ce63d6679.png)

Plugin is _on_. Press CTRL+A in the password field to select its contents. So misleading…

![image](https://user-images.githubusercontent.com/373718/201123152-90c4382c-91d8-45b5-9db9-db23541795e6.png)

**Comment by Rookiestyle** [comment]
Unfortunately that's the standard behaviour of a RichTextBox which needs to be used to show colors.
This is done by .Net and not within my span of control 

I agree this is not great, but I can't change it 

Most likely you select all to copy the password?
The copy in your clipboard will not contain additional spaces, this is a display issue in .Net only.

**Comment by Rookiestyle** [comment]
Some more links describing this behaviour 
https://github.com/Rookiestyle/ColoredPassword/issues/9#issuecomment-771442756
