### ISSUE TITLE
Selecting multiple entries cauuses display problems when using Dark Mode

### ISSUE THREAD

**Issue by ForgeSource** [Rookiestyle/ColoredPassword#21]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)

When using Dark Mode (via the KeeTheme plugin), selecting multiple entries causes text display for all columns other than Password in entry list to corrupt.

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Install KeeTheme plugin and set to Dark Mode.
2. Install ColoredPassword and set "Color passwords in entry list"
3. Select a number of entries in the Entry List view (e.g. with <CTRL>-A)
4. Observe that all columns other than Password display incorrectly. They seem to display twice, with one set slightly offset to the right.

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)

Expect display of columns other than Password to not be altered in any way.

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)

All columns other than Password display incorrectly. They seem to display twice, with one set slightly offset to the right.
Removing ColoredPassword, or removing Kee Theme, or setting Kee Theme to not use Dark Mode all resolve the issue. (But I'm trying to achieve coloured passwords with a dark mode).

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 11 Pro
KeePass Version: 2.53 (64-bit)
Plugin Version: 0.15

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
![image](https://user-images.githubusercontent.com/36454520/213231897-2a040800-6573-48e8-ae9e-2639f772d8a9.png)

This is how it looks like for me.
I don't see doubled display of all columns except the password column.

Which version of KeeTheme do you use?
Please post a screenshot

**Comment by ForgeSource** [comment]
Many thanks!

This is what I see when I select all entries (compared with none selected).

KeeTheme version is 0.10.2.0

![Test selected](https://user-images.githubusercontent.com/49476263/213306293-b3408356-72c5-441e-85c5-f47988541e37.png)
![Test unselected](https://user-images.githubusercontent.com/49476263/213306298-eee2a4d7-84af-4c53-8419-db4e0ce774bb.png)

**Comment by Rookiestyle** [comment]
I still can't reproduce it unfortunately.

Do you have other plugins installed besides KeeTheme and ColoredPassword?

**Comment by ForgeSource** [comment]
Thank you for trying. I had 3 other PlugIns - YetAnotherFaviconDownloader, NotesFontSelector and KeePassRPC installed. I have tried removing all of these, and restarted KeePass but it has made no difference to the issue.

Also, I was mistaken in saying that I need to "Select All" for the issue to manifest itself. Selecting a Single entry in the Entry List does the same. On closer inspection, it also looks as if the whole entry is being duplicated one space to the right; if you look at the screen shots above, and look at the password field, you can see that the last character is duplicated (uncoloured) at the right of the field.

I'm attaching a couple of additional screenshots showing how I have ColoredPassword configured, in case that helps.
![Plugins2](https://user-images.githubusercontent.com/49476263/213513012-cb7839bc-bbae-4cc5-9cf1-5cbadaaeff68.png)
![Plugins1](https://user-images.githubusercontent.com/49476263/213513015-97eb607c-c549-4947-9b22-31f9ee73f0ea.png)
![Plugins3](https://user-images.githubusercontent.com/49476263/213513017-65fdc945-aa93-4605-93ed-fae7d32a93fe.png)

**Comment by Rookiestyle** [comment]
OK, I could finally reproduce it.

Both plugins change the entry list in a special way. This way is called `OwnerDraw` and tells the OS to don't do anything.
The complete content (text, icons, chexkboxes, ...) of the listview has to be drawn by the plugins.

If KeePass loads KeeTheme prior to loading ColoredPassword, both plugins draw the entrylist and there is a small gap regarding the position of all the content including the texts.
If KeePass loads ColoredPassword prior to KeeTheme, KeeTheme detects that `OwnerDraw` is already activ and does not draw anything at all.

The attached version will remove KeeTheme's drawing routine to compensate the first case.

Let me know your results with this version.
If fine for you as well, I'll release after removing my debug message.
[ColoredPassword.zip](https://github.com/Rookiestyle/ColoredPassword/files/10460274/ColoredPassword.zip)

**Comment by ForgeSource** [comment]
Yes, I can confirm that this version fixes it.

Thank you VERY much for the time spent both providing and supporting this plug-in. I really appreciate it.
