### ISSUE TITLE
Colored password in KPEnhancedEntryView

### ISSUE THREAD

**Issue by Opicka879** [Rookiestyle/ColoredPassword#23]
Hello,

please consider adding support for displaying colored passwords in the KPEnhancedEntryView plugin.

Thank you :)

**Comment by Opicka879** [comment]
If the other protected fields were also colored, it would be best.

**Comment by Rookiestyle** [comment]
This needs to be implemented in KPEnhancedEntryView.
I brought it to the author's awareness =>https://sourceforge.net/p/kpenhentryview/discussion/general/thread/20e7f44445/

If implementied, it should work for all protected fields not only for passwords.

**Comment by Opicka879** [comment]
Thank you and the other plugin author too. You are awesome guys :)
