### ISSUE TITLE
Current releasedies not work with KeePass 2.44

### ISSUE THREAD

**Issue by maierei** [Rookiestyle/ColoredPassword#25]
## Overview
Current release of 0.15.2 does not work with KeePass 2.44

Could you please fix this?

Thank you.

**Comment by Rookiestyle** [comment]
You should observe this since version 0.15 as this release is the first one that respects editing multiple entries simultaneously.
The minimum release information is not up to date and I'm gonna fix that.

Please use minimum KeePass 2.46.
