### ISSUE TITLE
Incompatible with Keepass 2.5.6

### ISSUE THREAD

**Issue by KapUttyy** [Rookiestyle/ColoredPassword#29]
I updated my KeePass to the new version 2.5.6 and now I am getting an incompatibility error with the plugin:
![image](https://github.com/Rookiestyle/ColoredPassword/assets/22011945/ed51ce33-4b6d-4e9a-8cc3-7963485f37bf)

**Comment by Rookiestyle** [comment]
The current version 0.15.4 released in October 2023 works fine with KeePass 2.56.

Please update to this version and let me know whether this solved your issue or not.
If not solved, please click  "Details" in the error message and post the content here.

**Comment by KapUttyy** [comment]
Unfortunately it did not solve the issue.

This issue occurs since the update to 2.56. Here are the details of the error message. Unfortunately some parts are in german:
![image](https://github.com/Rookiestyle/ColoredPassword/assets/22011945/00f181ca-ce73-41bf-8e67-43c46f1299d6)

It should translate to something like: "The process is invalid due to the state of the object."

Best regards
Alex

**Comment by KapUttyy** [comment]
Nevermind, seems to be related to our used application control for IT-security reasons.

**Comment by Rookiestyle** [comment]
> Nevermind, seems to be related to our used application control for IT-security reasons.

I'm not sure about that.
Please run KeePass in debug mode by adding `--debug`. Instead of `KeePass.exe` in e. g. the shortcut you use, you need to use `KeePass.exe --debug`
You should see a message like below, please upload the file that is linked in the message
![image](https://github.com/Rookiestyle/ColoredPassword/assets/36454520/98935249-e517-420b-ba8b-dbc96f915d8d)

**Comment by KapUttyy** [comment]
I am sure now.
Our networks application control blocked the execution of .Net Frameworks csc.exe for being launched by the Keepass Process.. After allowing that the compilation worked fine and the plugin works again like a charm. Thanks for the support!
