### ISSUE TITLE
Marking capitilized letters

### ISSUE THREAD

**Issue by MissUnikitty** [Rookiestyle/ColoredPassword#4]
Hi, thanks for the great plug-in, it really helps when having dislexia and auto-fill is not available.

Yet, i did not find any option to mark/show capitilized letters, where i have allot of problems with.

Thank you.

**Comment by Rookiestyle** [comment]
I'm not sure what you're looking for exactly.

You can do the following already (example):
* Use blue color for as default
* Use green color for special chars
* Use red color for digits
* Activate *Different color for lowercase letters* and use purple for lowercase letters
This will result in blue color used for uppercase letters only

If that's not what you're looking for, please give an example that explains your request more in detail

**Comment by Rookiestyle** [comment]
Closed due to inactivity.

If above instructions don't help, let me know and I'll reopen this issue.

**Comment by MissUnikitty** [comment]
> I'm not sure what you're looking for exactly.
> 
> You can do the following already (example):
> 
> * Use blue color for as default
> * Use green color for special chars
> * Use red color for digits
> * Activate _Different color for lowercase letters_ and use purple for lowercase letters
>   This will result in blue color used for uppercase letters only
> 
> If that's not what you're looking for, please give an example that explains your request more in detail

Sorry i had a older version, problem solved.
