### ISSUE TITLE
'Paste' from context menu into Password field appends rather than overwrites

### ISSUE THREAD

**Issue by WalterEagle** [Rookiestyle/ColoredPassword#5]
SYMPTOMS
I occasionally require to paste a new password (generated outside KeePass) in to an entry to update it.
I have found when using the ColoredPassword plugin that pasting from the context menu does not operate correctly. It always appends the new entry rather than overwriting.

HOW TO DEMONSTRATE
I recommend using a new dummy database entry to test these instructions rather than risk corrupting a real existing password. 

1. Open the Edit Entry window for the test entry
2. Unhide the password
3. Highlight the entire password by double-clicking on any part of it
4. Right-click to show context menu and select 'Copy'
5. Right-click to show context menu and select 'Paste'

Instead of pasting the existing password characters on top of the existing password characters (i.e. no change), this action appends the password to itself. 
Alternatively, at Steps 3, 4 and 5, try using Ctrl+A, Ctrl+C and Ctrl+V to select, copy and paste. This works correctly, simply overwriting the password.
Using the context menu as in Steps 3 and 4, but using Ctrl+V to paste also works correctly.

As there is a procedure that does work correctly (using keyboard) this does not need to be regarded as urgent or important.
However I would like to have the option of using the context menu at some point in a future release.

 Thank you, keep well and best wishes

**Comment by Rookiestyle** [comment]
Good catch, thanks for letting me know

**Comment by WalterEagle** [comment]
Wow - excellent service! You're extremely prompt and very effective.
It works like a dream now.
This is a great plugin all-round.

Many thanks
