### ISSUE TITLE
Ctrl+A shows an extra blank character

### ISSUE THREAD

**Issue by juanbretti** [Rookiestyle/ColoredPassword#9]
Hello,
I have version 0.11.5.
When I'm visualizing a password.
I try to select all the password using Ctrl+A, an extra blank character is selected. This extra character is not copied, but looks like is selected.

Here is what the password looks like:
<img width="366" alt="visible" src="https://user-images.githubusercontent.com/10165911/106509009-514ce800-64cd-11eb-8840-c98a9b330ae5.png">

Here is the password selected using Ctrl+A:
<img width="366" alt="control_a" src="https://user-images.githubusercontent.com/10165911/106509043-60339a80-64cd-11eb-8755-544d72274c32.png">

**Comment by Rookiestyle** [comment]
This seems to be standard behaviour of the standard RichTextBox control as mentioned here:
https://stackoverflow.com/questions/7798451/richtextbox-invisible-selectable-character-at-end-of-string
https://social.msdn.microsoft.com/Forums/en-US/d3fc5ab2-7fa7-48b8-90f4-781e86d5317a/richtextbox-invisible-selectable-character-at-end-of-string

Changing this standard behaviour would require to hook into the way the OS handles this and this would require extensive testing.
As of now I do see this as a very minor topic that does not cause any issues beside looking a bit irritating.

Do you actually face issues?
if yes, I'll have a closer look to see how I can bypass the standard OS behaviour

**Comment by juanbretti** [comment]
Thank you for your reply. No, I don't face any issues at all.
It's just a cosmetic thing.

Do you want me to close this issue?

**Comment by Rookiestyle** [comment]
That was quick, thanks :-)

**Comment by sergeevabc** [comment]
@Rookiestyle, thanks for the [links](https://github.com/Rookiestyle/ColoredPassword/issues/9#issuecomment-771442756). It seems Microsoft failed us, again. Removed your plugin in the end, because relatives complained that they couldn't tell the real space from the non-existent one. Machines are here to help, not to bring more quirks.
